server:
  port: 8081
spring:
  messages:
    basename: ${messages.basename:messages}
    encoding: UTF-8
  liquibase:
    change-log: ${path.changelog:changeLog.xml}
    enabled: true
  datasource:
    username: ${datasource.username:postgres}
    password: ${datasource.password:1234}
    driver-class-name: ${datasource.driver:org.postgresql.Driver}
    url: ${datasource.url:jdbc:postgresql://localhost:5432/rest_api_basics_db}
    type: ${datasource.type:org.apache.commons.dbcp2.BasicDataSource}
    dbcp2:
      initial-size: ${pool.size:8}
      max-total: ${pool.total:32}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
    com:
      epam:
        esm:
          model:
            creator: DEBUG


#  main:
#    allow-bean-definition-overriding: true
#debug: true